package main.resources.medicalCentre;

import javax.swing.JOptionPane;

/**
 *
 * @author raghavendhra
 */

public class AppointmentMainPage extends javax.swing.JFrame {
    public static int ea = 0;

    /**
     * Creates new form ChooseAppointment
     */
    public AppointmentMainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLogOutButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPreviousButton = new javax.swing.JButton();
        jBookButton = new javax.swing.JButton();
        jUpcomingButton = new javax.swing.JButton();
        jHomeButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1550, 825));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        jPanel1.setBackground(new java.awt.Color(14, 94, 111));
        jPanel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1550, 195));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("AMRITA HOSPITAL");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicalCentre/asset/hospitalIcon.png"))); // NOI18N
        jLabel1.setText("\n");

        jLogOutButton.setBackground(new java.awt.Color(3, 153, 153));
        jLogOutButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        jLogOutButton.setForeground(new java.awt.Color(255, 255, 255));
        jLogOutButton.setText("LOG OUT\n");
        jLogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 378, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(319, 319, 319)
                .addComponent(jLogOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLogOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1608, -1));

        jPanel4.setLayout(null);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel4.setText("Healthcare with a Heart : Our founder, Sri Mata ");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(960, 240, 470, 27);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel8.setText("Amritananadamayi Devi (known as AMMA), envisioned ");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(960, 270, 500, 27);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel10.setText("creating a not-for-profit top hospital in Kerala, India ");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(960, 300, 500, 27);

        jLabel5.setBackground(new java.awt.Color(51, 204, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel5.setText("where the poor could have access to advanced medical   ");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(960, 330, 510, 27);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel11.setText("care in an atmosphere of love and compassion. Amrita ");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(960, 360, 520, 27);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel9.setText("Institute of Medical Sciences is now a world-class");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(960, 390, 470, 27);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel6.setText("institution of medicine, academics, and research.");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(960, 420, 470, 27);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicalCentre/asset/amma.jpg"))); // NOI18N
        jPanel4.add(jLabel3);
        jLabel3.setBounds(180, 210, 750, 270);

        jPreviousButton.setBackground(new java.awt.Color(0, 127, 63));
        jPreviousButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        jPreviousButton.setForeground(new java.awt.Color(255, 255, 255));
        jPreviousButton.setText("PREVIOUS APPOINTMENTS");
        jPreviousButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPreviousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPreviousButtonActionPerformed(evt);
            }
        });
        jPanel4.add(jPreviousButton);
        jPreviousButton.setBounds(520, 700, 410, 50);

        jBookButton.setBackground(new java.awt.Color(0, 127, 63));
        jBookButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        jBookButton.setForeground(new java.awt.Color(255, 255, 255));
        jBookButton.setText("BOOK APPOINTMENT");
        jBookButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBookButtonActionPerformed(evt);
            }
        });
        jPanel4.add(jBookButton);
        jBookButton.setBounds(520, 520, 410, 50);

        jUpcomingButton.setBackground(new java.awt.Color(0, 127, 63));
        jUpcomingButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        jUpcomingButton.setForeground(new java.awt.Color(255, 255, 255));
        jUpcomingButton.setText("UPCOMING APPOINTMENTS");
        jUpcomingButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jUpcomingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpcomingButtonActionPerformed(evt);
            }
        });
        jPanel4.add(jUpcomingButton);
        jUpcomingButton.setBounds(520, 610, 410, 50);

        jHomeButton.setBackground(new java.awt.Color(3, 153, 153));
        jHomeButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        jHomeButton.setForeground(new java.awt.Color(255, 255, 255));
        jHomeButton.setText("BACK");
        jHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHomeButtonActionPerformed(evt);
            }
        });
        jPanel4.add(jHomeButton);
        jHomeButton.setBounds(30, 210, 120, 50);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicalCentre/asset/Choose Appoin - Copy.png"))); // NOI18N
        jPanel4.add(jLabel13);
        jLabel13.setBounds(850, 410, 440, 410);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicalCentre/asset/FrontpageBackground.png"))); // NOI18N
        jPanel4.add(jLabel7);
        jLabel7.setBounds(0, 190, 1550, 640);

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 1550, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHomeButtonActionPerformed
        Main m = new Main();
        dispose();
        m.setVisible(true);
    }//GEN-LAST:event_jHomeButtonActionPerformed

    private void jProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        ManageProfile mp = new ManageProfile();
        dispose();
        mp.setVisible(true);
    }// GEN-LAST:event_jButton1ActionPerformed

    private void jBookButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        SelectSpecialisation s = new SelectSpecialisation();
        dispose();
        s.setVisible(true);
    }// GEN-LAST:event_jButton2ActionPerformed

    private void jUpcomingButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
        ViewAppointments ea = new ViewAppointments();
        dispose();
        ea.setVisible(true);
    }// GEN-LAST:event_jButton3ActionPerformed

    private void jPreviousButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
        AppointmentHistory ap = new AppointmentHistory();
        dispose();
        ap.setVisible(true);
    }// GEN-LAST:event_jButton4ActionPerformed

    private void jLogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton5ActionPerformed
        int ans = JOptionPane.showConfirmDialog(null, "Are you sure you want to log out?",
                        "Warning", JOptionPane.YES_NO_OPTION);
        if (ans == JOptionPane.YES_OPTION) {    
            FrontPage fp = new FrontPage();
            dispose();
            fp.setVisible(true);
        } 
    }// GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppointmentMainPage.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppointmentMainPage.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppointmentMainPage.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppointmentMainPage.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppointmentMainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBookButton;
    private javax.swing.JButton jHomeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jLogOutButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jPreviousButton;
    private javax.swing.JButton jUpcomingButton;
    // End of variables declaration//GEN-END:variables
}
