package main.resources.medicalCentre;

import java.awt.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raghavendhra
 */
public class AppointmentHistory extends javax.swing.JFrame {

    /**
     * Creates new form AppointmentHistory
     */
    public AppointmentHistory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLogOutButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jNewButton = new javax.swing.JButton();
        jUpcomingButton = new javax.swing.JButton();
        jBackButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1550, 825));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(14, 93, 109));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("AMRITA HOSPITAL");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicalCentre/asset/hospitalIcon.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 11, 162, -1));

        jLogOutButton.setBackground(new java.awt.Color(3, 153, 153));
        jLogOutButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        jLogOutButton.setForeground(new java.awt.Color(255, 255, 255));
        jLogOutButton.setText("LOG OUT");
        jLogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogOutButtonActionPerformed(evt);
            }
        });
        jPanel1.add(jLogOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1317, 63, 173, 59));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1550, -1));

        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicalCentre/asset/clipboard.png"))); // NOI18N
        jLabel3.setText("YOUR PREVIOUS APPOINTMENTS");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(450, 180, 660, 100);

        jNewButton.setBackground(new java.awt.Color(0, 102, 51));
        jNewButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jNewButton.setForeground(new java.awt.Color(255, 255, 255));
        jNewButton.setText("BOOK NEW APPOINTMENT");
        jNewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNewButtonActionPerformed(evt);
            }
        });
        jPanel2.add(jNewButton);
        jNewButton.setBounds(360, 730, 410, 50);

        jUpcomingButton.setBackground(new java.awt.Color(0, 102, 51));
        jUpcomingButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jUpcomingButton.setForeground(new java.awt.Color(255, 255, 255));
        jUpcomingButton.setText("UPCOMING APPOINTMENT");
        jUpcomingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpcomingButtonActionPerformed(evt);
            }
        });
        jPanel2.add(jUpcomingButton);
        jUpcomingButton.setBounds(790, 730, 410, 50);

        jBackButton.setBackground(new java.awt.Color(3, 153, 153));
        jBackButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        jBackButton.setForeground(new java.awt.Color(255, 255, 255));
        jBackButton.setText("BACK");
        jBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackButtonActionPerformed(evt);
            }
        });
        jPanel2.add(jBackButton);
        jBackButton.setBounds(110, 280, 105, 50);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "APPOINtMENT ID", "APPOINTMENT DATE", "APPOINTMENT TIME", "DOCTOR NAME", "SPECIALISATION"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(360, 280, 840, 430);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicalCentre/asset/Appointment_icon.png"))); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(1130, 400, 420, 430);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicalCentre/asset/FrontpageBackground.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 170, 1550, 660);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1550, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/onestopmedicalcentre", "root",
                    "WinMyDowSQL119");// TODO add your handling code here:
            
            Statement stmt = conn.createStatement();
            ResultSet appointmentTable = stmt.executeQuery(
                "select a.APPOINTMENT_ID, a.APPOINTMENT_DATE, a.APPOINTMENT_TIME, d.DOCTOR_NAME, d.DOCTOR_SPEC from appointment as a,doctor as d where a.DOCTOR_ID = d.DOCTOR_ID and a.APPOINTMENT_DATE < sysdate() and a.USER_ID = " +
                    Login.userIDInput + " order by a.APPOINTMENT_DATE desc");
            
            while(appointmentTable.next()){
                String appointmentID = appointmentTable.getString("a.APPOINTMENT_ID");
                String appointmentDate = appointmentTable.getString("a.APPOINTMENT_DATE");
                String appointmentTime = appointmentTable.getString("a.APPOINTMENT_TIME");
                String doctorName = appointmentTable.getString("d.DOCTOR_NAME");
                String doctorSpec = appointmentTable.getString("d.DOCTOR_SPEC");
                
                String tbData[] = {appointmentID, appointmentDate, appointmentTime, doctorName, doctorSpec};
                    DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
                    tblModel.addRow(tbData);
            }
            
            conn.close();
        }catch(Exception e){
            e.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jNewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNewButtonActionPerformed
        SelectSpecialisation s = new SelectSpecialisation();
        dispose();
        s.setVisible(true); 
    }//GEN-LAST:event_jNewButtonActionPerformed

    private void jUpcomingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpcomingButtonActionPerformed
        ViewAppointments va = new ViewAppointments();
        dispose();
        va.setVisible(true);        
    }//GEN-LAST:event_jUpcomingButtonActionPerformed

    private void jBackButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AppointmentMainPage ca = new AppointmentMainPage();
        dispose();
        ca.setVisible(true);
    }// GEN-LAST:event_jButton1ActionPerformed

    private void jLogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        int ans = JOptionPane.showConfirmDialog(null, "Are you sure you want to log out?",
                        "Warning", JOptionPane.YES_NO_OPTION);
        if (ans == JOptionPane.YES_OPTION) {    
            FrontPage fp = new FrontPage();
            dispose();
            fp.setVisible(true);
        } 
    }// GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppointmentHistory.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppointmentHistory.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppointmentHistory.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppointmentHistory.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppointmentHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBackButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jLogOutButton;
    private javax.swing.JButton jNewButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jUpcomingButton;
    // End of variables declaration//GEN-END:variables
}
