package main.resources.medicalCentre;
/**
 *
 * @author raghavendhra
 */
public class Specialisation extends javax.swing.JFrame {
    public static String docName;
    /**
     * Creates new form Specilization
     */
    public Specialisation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        Neurologist = new javax.swing.JToggleButton();
        Ophthalmologist = new javax.swing.JToggleButton();
        Otolaryngologist = new javax.swing.JToggleButton();
        Pulmonologist = new javax.swing.JToggleButton();
        jButton3 = new javax.swing.JButton();
        Gastroenterologist = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(14, 94, 111));
        jPanel1.setMaximumSize(new java.awt.Dimension(1550, 32767));
        jPanel1.setPreferredSize(new java.awt.Dimension(1550, 182));

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(14, 94, 111));
        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        label1.setForeground(java.awt.Color.white);
        label1.setName(""); // NOI18N
        label1.setText("Amrita Hospital");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicalCentre/asset/hospitalIcon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 1195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel5.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 7020, -1));

        jButton1.setBackground(new java.awt.Color(2, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setLabel("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 190, 136, 48));

        jToggleButton1.setBackground(new java.awt.Color(2, 153, 153));
        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setText("LOG OUT");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 190, 136, 48));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Select Specialization");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, -1, -1));

        Neurologist.setBackground(new java.awt.Color(0, 102, 102));
        Neurologist.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Neurologist.setForeground(java.awt.Color.white);
        Neurologist.setText("Neurologist");
        Neurologist.setMargin(new java.awt.Insets(2, 2, 2, 2));
        Neurologist.setMaximumSize(new java.awt.Dimension(208, 33));
        Neurologist.setMinimumSize(new java.awt.Dimension(208, 33));
        Neurologist.setPreferredSize(new java.awt.Dimension(208, 33));
        Neurologist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NeurologistActionPerformed(evt);
            }
        });
        jPanel5.add(Neurologist, new org.netbeans.lib.awtextra.AbsoluteConstraints(1105, 450, 210, 50));

        Ophthalmologist.setBackground(new java.awt.Color(0, 102, 102));
        Ophthalmologist.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Ophthalmologist.setForeground(java.awt.Color.white);
        Ophthalmologist.setText("Ophthalmologist");
        Ophthalmologist.setMargin(new java.awt.Insets(2, 2, 2, 2));
        Ophthalmologist.setMaximumSize(new java.awt.Dimension(208, 33));
        Ophthalmologist.setMinimumSize(new java.awt.Dimension(208, 33));
        Ophthalmologist.setPreferredSize(new java.awt.Dimension(208, 33));
        Ophthalmologist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OphthalmologistActionPerformed(evt);
            }
        });
        jPanel5.add(Ophthalmologist, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 730, 210, 50));

        Otolaryngologist.setBackground(new java.awt.Color(0, 102, 102));
        Otolaryngologist.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Otolaryngologist.setForeground(java.awt.Color.white);
        Otolaryngologist.setText("Otolaryngologist");
        Otolaryngologist.setMargin(new java.awt.Insets(2, 2, 2, 2));
        Otolaryngologist.setMaximumSize(new java.awt.Dimension(208, 33));
        Otolaryngologist.setMinimumSize(new java.awt.Dimension(208, 33));
        Otolaryngologist.setPreferredSize(new java.awt.Dimension(208, 33));
        Otolaryngologist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtolaryngologistActionPerformed(evt);
            }
        });
        jPanel5.add(Otolaryngologist, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 730, 210, 50));

        Pulmonologist.setBackground(new java.awt.Color(0, 102, 102));
        Pulmonologist.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Pulmonologist.setForeground(java.awt.Color.white);
        Pulmonologist.setText("Pulmonologist");
        Pulmonologist.setMargin(new java.awt.Insets(2, 2, 2, 2));
        Pulmonologist.setMaximumSize(new java.awt.Dimension(208, 33));
        Pulmonologist.setMinimumSize(new java.awt.Dimension(208, 33));
        Pulmonologist.setPreferredSize(new java.awt.Dimension(208, 33));
        Pulmonologist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PulmonologistActionPerformed(evt);
            }
        });
        jPanel5.add(Pulmonologist, new org.netbeans.lib.awtextra.AbsoluteConstraints(1105, 730, 210, 50));

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton3.setForeground(java.awt.Color.white);
        jButton3.setText("Cardiologist");
        jButton3.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton3.setMaximumSize(new java.awt.Dimension(208, 33));
        jButton3.setMinimumSize(new java.awt.Dimension(208, 33));
        jButton3.setPreferredSize(new java.awt.Dimension(208, 33));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 450, 210, 50));

        Gastroenterologist.setBackground(new java.awt.Color(0, 102, 102));
        Gastroenterologist.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Gastroenterologist.setForeground(java.awt.Color.white);
        Gastroenterologist.setText("Gastroenterologist");
        Gastroenterologist.setMargin(new java.awt.Insets(2, 2, 2, 2));
        Gastroenterologist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GastroenterologistActionPerformed(evt);
            }
        });
        jPanel5.add(Gastroenterologist, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 450, 210, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicalCentre/asset/1.png"))); // NOI18N
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicalCentre/asset/2.png"))); // NOI18N
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicalCentre/asset/3.png"))); // NOI18N
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 520, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicalCentre/asset/4.png"))); // NOI18N
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 520, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicalCentre/asset/5.png"))); // NOI18N
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 240, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicalCentre/asset/6.png"))); // NOI18N
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(6246, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1046, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CardiologistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardiologistActionPerformed
        // TODO add your handling code here:
        docName = "Cardiologist";
        SelectDoctor s = new SelectDoctor();
        dispose();
        s.setVisible(true);
        
    }//GEN-LAST:event_CardiologistActionPerformed

    private void PulmonologistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PulmonologistActionPerformed
        // TODO add your handling code here:
        docName = "Pulmonologist";
        SelectDoctor s = new SelectDoctor();
        dispose();
        s.setVisible(true);
    }//GEN-LAST:event_PulmonologistActionPerformed

    private void GastroenterologistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GastroenterologistActionPerformed
        // TODO add your handling code here:
        docName = "Gastroenterologist";
        SelectDoctor s = new SelectDoctor();
        dispose();
        s.setVisible(true);
    }//GEN-LAST:event_GastroenterologistActionPerformed

    private void OphthalmologistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OphthalmologistActionPerformed
        // TODO add your handling code here:
        docName = "Ophthalmologist";
        SelectDoctor s = new SelectDoctor();
        dispose();
        s.setVisible(true);
        
    }//GEN-LAST:event_OphthalmologistActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ChooseAppointment mp = new ChooseAppointment();
        dispose();
        mp.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        FrontPage fp = new FrontPage();
        dispose();
        fp.setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void NeurologistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NeurologistActionPerformed
        // TODO add your handling code here:
         docName = "Neurologist";
        SelectDoctor s = new SelectDoctor();
        dispose();
        s.setVisible(true);
    }//GEN-LAST:event_NeurologistActionPerformed

    private void OtolaryngologistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtolaryngologistActionPerformed
        // TODO add your handling code here:
        docName = "Otolaryngologist";
        SelectDoctor s = new SelectDoctor();
        dispose();
        s.setVisible(true);
    }//GEN-LAST:event_OtolaryngologistActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        docName = "Cardiologist";
        SelectDoctor s = new SelectDoctor();
        dispose();
        s.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Specialisation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Specialisation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Specialisation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Specialisation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Specialisation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Gastroenterologist;
    private javax.swing.JToggleButton Neurologist;
    private javax.swing.JToggleButton Ophthalmologist;
    private javax.swing.JToggleButton Otolaryngologist;
    private javax.swing.JToggleButton Pulmonologist;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JToggleButton jToggleButton1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
